---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard 
  resources:
    requests:
      storage: 10Gi
