apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: monitoring
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: grafanadb
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: grafana-secret-ha
              key: grafanadb-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-secret-ha
              key: grafanadb-password
        volumeMounts:
        - mountPath: /var/lib/postgresql/
          name: postgres-volume
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres-volume
