apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels: 
    app: grafana-deployment
    component: grafana-core
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
      app: grafana-deployment
      component: grafana-core
